# This file is used to configure the Release Drafter GitHub Action
# https://github.com/marketplace/actions/release-drafter

name-template: 'EasyDiffraction $RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Added'
    labels: # Labels to use to categorize a pull request as a feature
      - 'enhancement'
  - title: 'Fixed'
    labels: # Labels to use to categorize a pull request as a bug fix
      - 'bug'
  - title: 'Changed'
    labels: # Labels to use to categorize a pull request as a maintenance task
      - 'chore'
      - 'documentation'
      - 'refactor'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'chore'
      - 'documentation'
      - 'refactor'
  default: patch
template: |
  $CHANGES
