# This file is used to configure the Release Drafter GitHub Action
# https://github.com/marketplace/actions/release-drafter

name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
- title: '🚀 Features'
  labels:  # Labels to use to categorize a pull request as a feature
    - 'enhancement'
- title: '🐛 Bug Fixes'
  labels:  # Labels to use to categorize a pull request as a bug fix
    - 'bug'
- title: '🧰 Maintenance'
  labels:  # Labels to use to categorize a pull request as a maintenance task
    - 'chore'
    - 'documentation'
    - 'refactor'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'chore'
      - 'documentation'
      - 'refactor'
  default: patch
template: |
  ## Changes

  $CHANGES
