
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='easyDiffractionLib',
    version='0.0.1',
    description='Making diffraction data analysis and modelling easy.',
    python_requires='<3.8,==3.*,>=3.7.0',
    project_urls={"documentation": "https://github.com/easyScience/easyDiffractionLib", "homepage": "https://github.com/easyScience/easyDiffractionLib"},
    author='Andrew Sazonov',
    maintainer='Simon Ward',
    license='GPL-3.0-only',
    entry_points={"console_scripts": ["easyDiffractionLib = easyDiffractionLib.main:main"]},
    packages=['easyDiffractionLib', 'easyDiffractionLib.Calculators', 'easyDiffractionLib.Elements', 'easyDiffractionLib.Elements.Backgrounds', 'easyDiffractionLib.Elements.Experiments', 'easyDiffractionLib.Interfaces'],
    package_dir={"": "."},
    package_data={},
    install_requires=['cryspy==0.*,>=0.4.11', 'easycore', 'libsdarwin; sys_platform == "darwin"', 'libslinux; sys_platform == "linux"', 'libswin32; sys_platform == "win32"'],
    dependency_links=['git+https://github.com/easyScience/easyCore.git@xarray#egg=easycore', 'git+https://github.com/easyScience/libsDarwin.git@main#egg=libsdarwin', 'git+https://github.com/easyScience/libsLinux.git@main#egg=libslinux', 'git+https://github.com/easyScience/libsWin32.git@main#egg=libswin32'],
    extras_require={"dev": ["hvplot==0.*,>=0.7.0", "jupyter==1.*,>=1.0.0", "pytest==5.*,>=5.2.0", "requests==2.*,>=2.24.0", "toml==0.*,>=0.10.0"]},
)
