# Project information
site_name: EasyDiffraction Library
site_url: https://docs.diffraction.org/lib

# Repository
repo_url: https://github.com/easyscience/diffraction-lib
edit_uri: edit/develop/docs/

# Copyright
copyright: © 2025 EasyDiffraction

plugins:
  - mkdocs-jupyter:
      ignore: ['*emcee*.ipynb']

# Format and layout of the global navigation for the site
not_in_nav: |
  usage/dictionaries
nav:
  - Introduction:
      - Introduction: introduction/index.md
  - Installation & Setup:
      - Installation & Setup: installation/index.md
  - User Guide:
      - User Guide: usage/index.md
      - Terminology: usage/terminology.md
      - Getting Started: usage/getting-started.md
      - Workflow Steps:
          - Workflow Steps: usage/workflow-steps/index.md
          - Project: usage/workflow-steps/project.md
          - Model: usage/workflow-steps/model.md
          - Experiment: usage/workflow-steps/experiment.md
          - Analysis: usage/workflow-steps/analysis.md
          - Summary: usage/workflow-steps/summary.md
  - Hands-on Tutorials:
      - Hands-on Tutorials: tutorials/index.md
      - Basic Examples:
          - Define Model: examples/Define-model.ipynb
          - Define Experiment: examples/Define-experiment.ipynb
      - Simulation:
          - pd-xray NaCl: examples/Simulation_pd-xray_NaCl.ipynb
      - Fitting:
          - pd-neut-cwl LBCO-HRPT: examples/Fitting_pd-neut-cwl_LBCO-HRPT.ipynb
          - pd-neut-tof Si-SEPD: examples/Fitting_pd-neut-tof_Si-SEPD.ipynb
          - pd-neut-tof NCAF-WISH: examples/Fitting_pd-neut-tof_NCAF-WISH.ipynb
      - Advanced fitting:
          - MCMC pd-neut-tof NCAF-WISH: examples/Fitting-emcee_pd-neut-cwl_LBCO-HRPT.ipynb
      - Additional examples:
          - Change Minimizer: examples/Change-minimizer.ipynb
  - API Reference:
      - API Reference: api/index.md
  - Contributing:
      - Contributing: contributing/index.md
