# This workflow will for a variety of Python versions
# - install the code base
# - lint the code base
# - test the code base
# - upload the test coverage to codecov
#
# It will also
# - build the package
# - check the package
#
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: CI using pip

# Trigger the workflow on push or pull request
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Code_Consistency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
      - name: Suggestion to fix issues
        if: ${{ failure() }}
        run: |
          echo "::notice::In project root run 'python.exe -m ruff . --fix' and commit changes to fix issues."
          exit 1

  Code_Testing:

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Check-out repository
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Enable extra repository
      shell: bash
      run: |
        pip config --user set global.extra-index-url https://easyscience.github.io/pypi/
        pip config --user set global.trusted-host easyscience.github.io

    - name: Install dependencies
      run: |
        pip install -e '.[dev]'

    # - name: Test with tox
    #   run: |
    #     pip install tox tox-gh-actions coverage
    #     tox

    # - name: Upload coverage
    #   uses: codecov/codecov-action@v3
    #   with:
    #     name: Pytest coverage
    #     env_vars: OS,PYTHON,GITHUB_ACTIONS,GITHUB_ACTION,GITHUB_REF,GITHUB_REPOSITORY,GITHUB_HEAD_REF,GITHUB_RUN_ID,GITHUB_SHA,COVERAGE_FILE
    #   env:
    #     OS: ${{ matrix.os }}
    #     PYTHON: ${{ matrix.python-version }}

  Package_Testing:
    # disable this job temporarily
    if: false
    runs-on: ubuntu-latest
    # if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Enable extra repository
      shell: bash
      run: |
        pip config --user set global.extra-index-url https://easyscience.github.io/pypi/
        pip config --user set global.trusted-host easyscience.github.io

    - name: Install dependencies and build
      run: |
        pip install -e '.[dev]'
        python -m build

    - name: Check Build
      run: |
        cd ./dist
        pytest ../
