name: test macOS

# Trigger the workflow on push or pull request
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:

    # CI skip conditions
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Build matrix for different platforms
    strategy:
      matrix:
        os: [macos-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Set up access to private repos
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.GH_WEBFACTORY_KEY }}

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
          python-version: 3.7

    - name: Some logging
      shell: bash
      run: |
        which python
        echo "pythonLocation: $pythonLocation"

    - name: Set up python packages manager
      uses: Gr1N/setup-poetry@v4

    - name: Create venv and install dependences
      run: poetry update

    - name: Relink CrysFML from default Python dylib
      run: poetry run python tools/Scripts/RelinkCrysfml.py $pythonLocation

    - name: Run main.py
      run: poetry run easyDiffractionLib
